In [1]:
import numpy as np

In [2]:
# random.randnt(max_int,size=(shape of array))
arr = np.random.randint(10,size=(3,5))
arr

array([[4, 4, 7, 6, 3],
       [5, 4, 3, 5, 4],
       [5, 3, 2, 0, 8]])

In [3]:
unique = np.unique(arr)
unique

array([0, 2, 3, 4, 5, 6, 7, 8])

In [4]:
np.random.seed(seed=2) # will keep the randomly genetrated numbers same
np.random.random(size=(3,5))

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987]])

In [5]:
np.random.seed(seed=2) # seed=2 is a type of id for the generated numbers
np.random.random(size=(3,5))

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987]])

In [9]:
new_arr = np.random.randint(10,size=(2,3,4,3))

In [7]:
new_arr[:1,:2,:2,:2]

array([[[[7, 6],
         [3, 5]],

        [[4, 2],
         [1, 7]]]])

In [24]:
ar1 = np.random.randint(10,size=(3,4))
ar2 = np.random.randint(10,size=(2,3,4))

In [25]:
ar1*ar2

array([[[18,  9, 30, 15],
        [20,  0, 24, 45],
        [ 9, 28,  8, 30]],

       [[ 2,  2,  0, 45],
        [ 5,  0,  8, 45],
        [ 4,  8,  8,  5]]])

In [29]:
print(np.sum(ar1),np.sum(ar2))

52 102


In [30]:
print(np.mean(ar1),np.mean(ar2))

4.333333333333333 4.25
