In [1]:
import numpy as np

In [2]:
# random.randnt(max_int,size=(shape of array))
arr = np.random.randint(10,size=(3,5))
arr

array([[9, 9, 3, 0, 3],
       [5, 6, 6, 0, 2],
       [7, 4, 9, 9, 0]])

In [3]:
unique = np.unique(arr)
unique

array([0, 2, 3, 4, 5, 6, 7, 9])

In [4]:
np.random.seed(seed=2) # will keep the randomly genetrated numbers same
np.random.random(size=(3,5))

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987]])

In [5]:
np.random.seed(seed=2) # seed=2 is a type of id for the generated numbers
np.random.random(size=(3,5))

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987]])

In [6]:
new_arr = np.random.randint(10,size=(2,3,4,3))

In [7]:
new_arr[:1,:2,:2,:2]

array([[[[7, 6],
         [3, 5]],

        [[4, 2],
         [1, 7]]]])

In [8]:
ar1 = np.random.randint(10,size=(3,4))
ar2 = np.random.randint(10,size=(2,3,4))

In [9]:
ar1*ar2

array([[[ 4, 27, 12,  1],
        [ 0,  0,  8, 40],
        [36,  0, 63,  0]],

       [[20,  6, 30,  1],
        [12,  0,  8, 40],
        [24, 16,  9, 35]]])

In [10]:
print(np.sum(ar1),np.sum(ar2))

53 93


In [11]:
print(np.mean(ar1),np.mean(ar2))

4.416666666666667 3.875


In [12]:
high_var_arr = np.array([1,234,456,700,1500,5000])
low_var_arr = np.array([1,4,7,8,10,15])

In [13]:
# variance is degree up to which each number is different to the mean
np.var(high_var_arr),np.var(low_var_arr)
# standard deviation = squareroot(variance)
np.std(high_var_arr),np.std(low_var_arr)

(1713.8996875222565, 4.425306015783918)

In [14]:
arr = np.random.randint(10,size=(3,3))
arr2 = np.random.randint(10,size=(3,2))
arr.dot(arr2)

array([[100,  87],
       [ 91,  56],
       [  8,  12]])

In [15]:
import pandas as pd
nut_sales = pd.read_csv('nut_butter_sales.csv')

In [16]:
nut_sales

day  almond  peanut  cashew
0  Mon       5       6       7
1  Tue       3       6       9
2  Wed       7       8       3
3  Thu       9       6       4
4  Fri      10      12       4

In [17]:
prices = np.array([10,8,12])

In [18]:
total_cost = prices.dot(nut_sales[['almond','peanut','cashew']].T)

In [19]:
nut_sales['total sales'] = total_cost
print(total_cost) # sales of monday , tuesday ... friday

[182 186 170 186 244]


In [20]:
nut_sales.rename(columns={'total sales':'total earnings'},inplace=True)

In [21]:
nut_sales

day  almond  peanut  cashew  total earnings
0  Mon       5       6       7             182
1  Tue       3       6       9             186
2  Wed       7       8       3             170
3  Thu       9       6       4             186
4  Fri      10      12       4             244

In [22]:
nut_sales['sales'] = nut_sales.loc[:,['almond','peanut','cashew']].sum(axis=1)

In [23]:
nut_sales
prices = np.array([10,8,12])
prices = pd.DataFrame(prices,columns=['price'])

In [24]:
prices['butter'] = ['almond','peanut','cashew']

In [25]:
prices

price  butter
0     10  almond
1      8  peanut
2     12  cashew

In [26]:
from matplotlib.image import imread
smiley = imread("smiley.bmp")
smiley.shape , smiley.ndim , smiley.size

((32, 32, 3), 3, 3072)

In [28]:
new_arr = np.random.randint(10,size=(3,3))
new_arr

array([[7, 3, 4],
       [8, 6, 3],
       [8, 8, 5]])

In [32]:
new_arr.sort()
new_arr

array([[3, 4, 7],
       [3, 6, 8],
       [5, 8, 8]])

In [35]:
new_arr.argmax(axis=1)

array([2, 2, 1], dtype=int64)